-- 코드를 입력하세요
SELECT A.HISTORY_ID, 
       CASE 
        WHEN A.END_DATE - A.START_DATE + 1 >= 7 
            then B.DAILY_FEE * ((100 - C.DISCOUNT_RATE) / 100) * ( A.END_DATE - A.START_DATE + 1)
        ELSE B.DAILY_FEE * (A.END_DATE - A.START_DATE + 1) END "FEE"
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
   , CAR_RENTAL_COMPANY_CAR B
   , CAR_RENTAL_COMPANY_DISCOUNT_PLAN C
WHERE A.CAR_ID = B.CAR_ID	
AND B.CAR_TYPE = C.CAR_TYPE
AND C.DURATION_TYPE LIKE 
    CASE WHEN (A.END_DATE - A.START_DATE + 1) BETWEEN 7 and 29 then '7일%'
         WHEN (A.END_DATE - A.START_DATE + 1) BETWEEN 30 and 89 then '30일%'
         WHEN (A.END_DATE - A.START_DATE + 1) >= 90 then '90일%'
         ELSE '7일%' END
AND B.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC