SELECT  A.EMP_NO
     , EMP_NAME
     , CASE
        WHEN AVG(SCORE) >= 96 THEN 'S'
        WHEN AVG(SCORE) < 96 AND AVG(SCORE) >= 90 THEN 'A'
        WHEN AVG(SCORE) < 90 AND AVG(SCORE) >= 80 THEN 'B'
        ELSE 'C'
       END AS GRADE
     , CASE
        WHEN AVG(SCORE) >= 96 THEN AVG(SAL) * 0.2
        WHEN AVG(SCORE) < 96 AND AVG(SCORE) >= 90 THEN AVG(SAL) * 0.15
        WHEN AVG(SCORE) < 90 AND AVG(SCORE) >= 80 THEN AVG(SAL) * 0.1
        ELSE AVG(SAL) * 0
       END AS BONUS
  FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
 GROUP BY EMP_NO
 ORDER BY EMP_NO