SELECT  A.ITEM_ID, A.ITEM_NAME, A.RARITY
  FROM ITEM_INFO A
  JOIN ITEM_TREE B ON A.ITEM_ID = B.ITEM_ID
  JOIN ITEM_INFO C ON C.ITEM_ID = B.PARENT_ITEM_ID
 WHERE C.RARITY = 'RARE'
 ORDER BY ITEM_ID DESC