-- 점수 사번 성명 직책 이메일 GROUP BY 절에 SELECT 하는 모든 컬럼이 안들어가는데도 오류가 안나는 이유?
SELECT  SUM(B.SCORE) AS SCORE, B.EMP_NO, A.EMP_NAME, A.POSITION, A.EMAIL
  FROM HR_EMPLOYEES A JOIN HR_GRADE B ON A.EMP_NO = B.EMP_NO
 GROUP BY EMP_NO
 ORDER BY SCORE DESC
 LIMIT 1