SELECT  COUNT(A.FISH_TYPE) AS FISH_COUNT
     , MAX(A.LENGTH) AS MAX_LENGTH
     , A.FISH_TYPE
  FROM FISH_INFO A 
  JOIN 
  (SELECT FISH_TYPE
        , AVG(IFNULL(LENGTH, 10)) AS MEAN
     FROM FISH_INFO
    GROUP BY FISH_TYPE) B
    ON A.FISH_TYPE = B.FISH_TYPE
 WHERE B.MEAN >= 33
 GROUP BY FISH_TYPE
 ORDER BY FISH_TYPE